# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

locations = [
  {city: "Marrakech", country: "Morocco", region: "Africa", latitude: 31.630000, longitude: -8.008889, description: "Marrakech is a major city in the northwest African nation of Morocco. It is the fourth largest city in the country after Casablanca, Rabat and Fes, and is the capital of the mid-southwestern region of Marrakesh-Tensift-El Haouz..."},
  {city: "Siem Reap", country: "Cambodia", region: "Southeast Asia", latitude: 13.380936, longitude: 103.875046, description: "Siem Reap is the capital city of Siem Reap Province in northwestern Cambodia, and a popular resort town as the gateway to Angkor region. Siem Reap has colonial and Chinese-style architecture in the Old French Quarter, and around..."},
  {city: "Istanbul", country: "Turkey", region: "Europe", latitude: 41.005270, longitude: 28.976960, description: "Istanbul is the largest city in Turkey, constituting the country's economic, cultural, and historical heart. Istanbul is a transcontinental city in Eurasia, with its commercial and historical centre lying on the European side and..."},
  {city: "Hanoi", country: "Vietnam", region: "Southeast Asia", latitude: 21.027764, longitude: 105.834160, description: "Hanoi is the capital of Vietnam and the country's second largest city. Its population in 2009 was estimated at 2.6 million for urban districts, 6.5 million for the metropolitan jurisdiction. From 1010 until 1802, it was the most..."},
  {city: "Prague", country: "Czech Republic", region: "Europe", latitude: 50.075538, longitude: 14.437800, description: "Prague is the capital and largest city of the Czech Republic. It is the fourteenth-largest city in the European Union. It is also the historical capital of Bohemia. Situated in the north-west of the country on the Vltava River, the..."},
  {city: "London", country: "United Kingdom", region: "Europe", latitude: 51.507351, longitude: -0.127758, description: "London is the capital and most populous city of England and the United Kingdom. Standing on the River Thames, London has been a major settlement for two millennia, its history going back to its founding by the Romans, who named it..." },
  {city: "Berlin", country: "Germany", region: "Europe", latitude: 52.520007, longitude: 13.404954, description: "Berlin is the capital of Germany, and one of the 16 states of Germany. With a population of 3.5 million people, Berlin is Germany's largest city. It is the second most populous city proper and the seventh most populous urban area..."},
  {city: "Rome", country: "Italy", region: "Europe", latitude: 41.902783, longitude: 12.496366, description: "Rome is a city and special comune (named ''Roma Capitale'') in Italy. Rome is the capital of Italy and region of Lazio. With 2.9 million residents in 1,285 km2 (496.1 sq mi), it is also the country's largest and most populated comune..."},
  {city: "Buenos Aires", country: "Argentina", region: "South America", latitude: -34.603723, longitude: -58.381593, description: "Buenos Aires is the capital and largest city of Argentina, and the second-largest metropolitan area in South America, after Greater São Paulo. It is located on the western shore of the estuary of the Río de la Plata, on the continent's..."},
  {city: "New York City", country: "United States", region: "North America", latitude: 40.712784, longitude: -74.005941, description: "New York – often called New York City or the City of New York to distinguish it from the State of New York, of which it is a part – is the most populous city in the United States and the center of the New York metropolitan area, the... "}
]

locations.each do |place_hash|
  loc = Location.find_by(place_hash[:city])
  loc.update(place_hash)
  end

Currency.seed_data

Location.find_by(city: "Marrakech").currency_locations.create(:currency => Currency.find_by(:symbol => "AED"))
Location.find_by(city: "Siem Reap").currency_locations.create(:currency => Currency.find_by(:symbol => "KHR"))
Location.find_by(city: "Istanbul").currency_locations.create(:currency => Currency.find_by(:symbol => "TRY"))
Location.find_by(city: "Hanoi").currency_locations.create(:currency => Currency.find_by(:symbol => "VND"))
Location.find_by(city: "Prague").currency_locations.create(:currency => Currency.find_by(:symbol => "CZK"))
Location.find_by(city: "London").currency_locations.create(:currency => Currency.find_by(:symbol => "GBP"))
Location.find_by(city: "Berlin").currency_locations.create(:currency => Currency.find_by(:symbol => "EUR"))
Location.find_by(city: "Rome").currency_locations.create(:currency => Currency.find_by(:symbol => "EUR"))
Location.find_by(city: "Buenos Aires").currency_locations.create(:currency => Currency.find_by(:symbol => "ARS"))
Location.find_by(city: "New York City").currency_locations.create(:currency => Currency.find_by(:symbol => "USD"))

languages = %w(Arabic Berber Central Khmer English Turkish Vietnamese Czech Slovak German Italian Spanish)
languages.each do |language|
  Language.create(:name => language)
end

Location.find_by(city: "Marrakech").language_locations.create(:language => Language.find_by(:name => "Arabic"))
Location.find_by(city: "Marrakech").language_locations.create(:language => Language.find_by(:name => "Berber"))
Location.find_by(city: "Siem Reap").language_locations.create(:language => Language.find_by(:name => "Central Khmer"))
Location.find_by(city: "Siem Reap").language_locations.create(:language => Language.find_by(:name => "English"))
Location.find_by(city: "Istanbul").language_locations.create(:language => Language.find_by(:name => "Turkish"))
Location.find_by(city: "Hanoi").language_locations.create(:language => Language.find_by(:name => "Vietnamese"))
Location.find_by(city: "Prague").language_locations.create(:language => Language.find_by(:name => "Czech"))
Location.find_by(city: "Prague").language_locations.create(:language => Language.find_by(:name => "Slovak"))
Location.find_by(city: "Prague").language_locations.create(:language => Language.find_by(:name => "English"))
Location.find_by(city: "London").language_locations.create(:language => Language.find_by(:name => "English"))
Location.find_by(city: "Berlin").language_locations.create(:language => Language.find_by(:name => "German"))
Location.find_by(city: "Berlin").language_locations.create(:language => Language.find_by(:name => "English"))
Location.find_by(city: "Rome").language_locations.create(:language => Language.find_by(:name => "Italian"))
Location.find_by(city: "Buenos Aires").language_locations.create(:language => Language.find_by(:name => "Spanish"))
Location.find_by(city: "Buenos Aires").language_locations.create(:language => Language.find_by(:name => "Italian"))
Location.find_by(city: "New York City").language_locations.create(:language => Language.find_by(:name => "English"))

# Lodging.seed_data

Location.find_by(city: "Marrakech").images.create({url: "https://farm9.staticflickr.com/8580/15680040273_2e3e51202b_b.jpg", source: "https://www.flickr.com/photos/marasweltreisen", image_type: "hero", caption: "Marrakech"})
Location.find_by(city: "Siem Reap").images.create({url: "https://farm8.staticflickr.com/7447/8718052701_2e1a6b64da_h.jpg", source: " https://www.flickr.com/photos/chrisbastian", image_type: "hero", caption: "Siem Reap"})
Location.find_by(city: "Istanbul").images.create({url: "https://farm4.staticflickr.com/3812/13806413813_6c35ef719c_b.jpg", source: "https://www.flickr.com/photos/ahmetkilci", image_type: "hero", caption: "Istanbul"})
Location.find_by(city: "Hanoi").images.create({url: "https://farm8.staticflickr.com/7233/7384948350_485e8e12af_b.jpg", source: "https://www.flickr.com/photos/jean-pierre-chudeau", image_type: "hero", caption: "Hanoi"})
Location.find_by(city: "Prague").images.create({url: "https://farm8.staticflickr.com/7422/10066191593_326757cdf3_b.jpg", source: "https://www.flickr.com/photos/65789667@N06", image_type: "hero", caption: "Prague"})
Location.find_by(city: "London").images.create({url: "https://farm8.staticflickr.com/7002/6564991705_c4af8baa66_b.jpg", source: "https://www.flickr.com/photos/38181284@N06", image_type: "hero", caption: "London"})
Location.find_by(city: "Berlin").images.create({url: "https://farm4.staticflickr.com/3824/11844962716_6ec011a82e_b.jpg", source: "https://www.flickr.com/photos/david-bank", image_type: "hero", caption: "Berlin"})
Location.find_by(city: "Rome").images.create({url: "https://farm6.staticflickr.com/5013/5481288261_7de58f0c95_b.jpg", source: " https://www.flickr.com/photos/aigle_dore", image_type: "hero", caption: "Rome"})
Location.find_by(city: "Buenos Aires").images.create({url: "https://farm8.staticflickr.com/7648/16939983051_2e8c4959ae_b.jpg", source: "https://www.flickr.com/photos/german_long", image_type: "hero", caption: "Buenos Aires"})
Location.find_by(city: "New York City").images.create({url: "https://farm9.staticflickr.com/8465/8116884592_f563d97f06_b.jpg", source: "https://www.flickr.com/photos/stephenwalford", image_type: "hero", caption: "New York City"})

# Image.seed_images

## New York Attractions
new_york = Location.find_by(city: "New York City")
Attraction.create(:name => "Statue of Liberty", :description => "The Statue of Liberty is a colossal neoclassical sculpture on Liberty Island in New York Harbor in New York City, in the United States. The statue, designed by Frédéric Auguste Bartholdi, a French sculptor and dedicated on October 28, 1886, was a gift to the United States from the people of France.", :attraction_type => "Landmarks" ,:location => new_york)
Attraction.create(:name => "Empire State Building", :description => "The Empire State Building is a 102-story skyscraper located in Midtown Manhattan, New York City, on Fifth Avenue between West 33rd and 34th Streets. It has a roof height of 1,250 feet (380 m), and with its antenna spire included, it stands a total of 1,454 feet (443 m) high. Its name is derived from the nickname for New York, the Empire State. It stood as the world's tallest building for nearly 40 years, from its completion in early 1931 until the topping out of the original World Trade Center's North Tower in late 1970. Following the September 11 attacks in 2001, the Empire State Building was again the tallest building in New York (although it was no longer the tallest in the US or the world), until One World Trade Center reached a greater height on April 30, 2012. The Empire State Building is currently the fourth-tallest completed skyscraper in the United States (after the One World Trade Center, the Willis Tower and Trump International Hotel and Tower, both in Chicago), and the 25th-tallest in the world (the tallest now is Burj Khalifa, located in Dubai). It is also the fifth-tallest freestanding structure in the Americas.", :attraction_type => "Landmarks" ,:location => new_york)
Attraction.create(:name => "One World Trade Center", :description => "One World Trade Center (also known as 1 World Trade Center, One WTC and 1 WTC; the current building was dubbed the Freedom Tower during initial basework) refers to the main building of the new World Trade Center complex in Lower Manhattan, New York City. It is the tallest skyscraper in the Western Hemisphere, and the fourth-tallest in the world. The 104-story supertall structure shares a numeric name with the northern Twin Tower of the original World Trade Center, which was destroyed in the terrorist attacks of September 11, 2001. The new skyscraper stands on the northwest corner of the 16-acre (6.5 ha) World Trade Center site, on the site of the original 6 World Trade Center. The building is bordered by West Street to the west, Vesey Street to the north, Fulton Street to the south, and Washington Street to the east.", :attraction_type => "Landmarks" ,:location => new_york)
Attraction.create(:name => "Colicchio & Sons", :description => "Established in 2010, borrowing from the historic High Line just outside its doors, the interior of Colicchio & Sons, with its vaulted ceilings, riveted steel columns and expansive windows, pays homage to its legendary former tenant, the National Biscuit Company. In Tap Room, guests can enjoy a menu of specialties from the wood-burning hearth, an extensive selection of artisan beers, as well as a distinctive wine list by the glass and bottle. The Main Dining Room menu focuses on seasonal dishes prepared with small-batch ingredients from micro-producers and family farmers.  In both food and décor, Colicchio & Sons is the restaurant where time-honored materials and techniques meet the inventiveness of a new and optimistic decade.", :attraction_type => "Dining" ,:location => new_york)
Attraction.create(:name => "Gramercy Tavern", :description => "One of America’s most beloved restaurants, Gramercy Tavern has welcomed guests to enjoy its contemporary American cuisine, warm hospitality, and unparalleled service for close to two decades. Chef Michael Anthony’s fiercely seasonal menu consists of elegant dishes with a rustic influence that showcase the restaurant’s relationships with local farms and purveyors.

The restaurant can be enjoyed through two distinct dining experiences: the Tavern and the Dining Room. The Tavern serves an à la carte menu in a casual, walk-in setting and offers a daily four-course tasting menu at dinner. The Dining Room offers fixed-price and tasting menus with an à la carte option at lunch.

Opened in 1994 by legendary restaurateur Danny Meyer in a historic landmark building, the restaurant is designed by Bentel & Bentel with murals from artist Robert Kushner and vibrant floral arrangements from Roberta Bendavid.", :attraction_type => "Dining" ,:location => new_york)
Attraction.create(:name => "Eleven Madison Park", :description => "Established in 1998, Eleven Madison Park embodies an urbane sophistication serving Chef Daniel Humm's modern, sophisticated French cuisine that emphasizes purity, simplicity and seasonal flavors and ingredients.  Daniel's delicate and precise cooking style is experienced through a constantly evolving menu. The restaurant's dramatically high ceilings and magnificent art deco dining room offer guests lush views of historic Madison Square Park and the Flatiron building. In addition to the main dining room, guests may also enjoy wine, beer, and cocktails, as well as an extensive bar menu in the restaurant's bar and Flatiron Lounge.
In November 2008, Eleven Madison Park was designated Grand Chef Relais & Châteaux, joining the ranks of one of the world's most exclusive associations of hotels and gourmet restaurants. In 2009, Eleven Madison Park received a Four Star Review from The New York Times. The restaurant was also awarded one Michelin star.", :attraction_type => "Dining" ,:location => new_york)
Attraction.create(:name => "Broadway", :description => "Broadway theatre, commonly known as Broadway, refers to the theatrical performances presented in the 40 professional theatres with 500 or more seats located in the Theater District and Lincoln Center along Broadway, in the New York City borough of Manhattan. Along with London's West End theatres, Broadway theatres are widely considered to represent the highest level of commercial theatre in the English-speaking world.

The Broadway Theater District is a popular tourist attraction in New York City. According to The Broadway League, Broadway shows sold a record US$1.36 billion worth of tickets in 2014, an increase of 14% over the previous year. Attendance in 2014 stood at 13.13 million, a 13% increase over 2013.

The great majority of Broadway shows are musicals. Historian Martin Shefter argues, \"'Broadway musicals,' culminating in the productions of Richard Rodgers and Oscar Hammerstein, became enormously influential forms of American popular culture\" and helped make New York City the cultural capital of the nation.", :attraction_type => "Other" ,:location => new_york)
Attraction.create(:name => "Central Park", :description => "Central Park is an urban park in the central part of the borough of Manhattan, New York City. It was initially opened in 1857, on 778 acres (315 ha) of city-owned land, later expanding to its current size of 843 acres (341 ha).

In 1858, soon-to-be famed national landscapers and architects, Frederick Law Olmsted and Calvert Vaux, won a design competition to improve and expand the park with a plan they titled the \"Greensward Plan\". Construction began the same year, continued during the American Civil War further south, and was completed in 1873. It was designated a National Historic Landmark (listed by the U.S. Department of the Interior and administered by the National Park Service) in 1962. The Park was managed for decades by the New York City Department of Recreation and Parks and is currently managed by the Central Park Conservancy under contract with the municipal government in a public-private partnership. The Conservancy is a non-profit organization that contributes 75% of Central Park's $57 million annual budget and employs 80.7% of the Park's maintenance staff.

Today, Central Park is the most visited urban park in the United States as well as one of the most filmed locations in the world.", :attraction_type => "Other" ,:location => new_york)
Attraction.create(:name => "The Metropolitan Museum of Art", :description => "The Metropolitan Museum of Art (colloquially The Met), located in New York City, is the largest art museum in the United States and one of the ten largest in the world. Its permanent collection contains more than two million works, divided among seventeen curatorial departments. The main building, located on the eastern edge of Central Park along Manhattan's Museum Mile, is by area one of the world's largest art galleries. There is also a much smaller second location at The Cloisters in Upper Manhattan that features medieval art.

Represented in the permanent collection are works of art from classical antiquity and Ancient Egypt, paintings and sculptures from nearly all the European masters, and an extensive collection of American and modern art. The Met also maintains extensive holdings of African, Asian, Oceanic, Byzantine, and Islamic art. The museum is also home to encyclopedic collections of musical instruments, costumes and accessories, and antique weapons and armor from around the world. Several notable interiors, ranging from first-century Rome through modern American design, are permanently installed in the Met's galleries.

The Metropolitan Museum of Art was founded in 1870. The founders included businessmen and financiers, as well as leading artists and thinkers of the day, who wanted to open a museum to bring art and art education to the American people. It opened on February 20, 1872, and was originally located at 681 Fifth Avenue.

As of 2012, the Met occupies about 2,000,000 square feet (190,000 m2). Admission is pay what you wish with a recommendation of $25.", :attraction_type => "Other" ,:location => new_york)

### Buenos Aires Attractions
buenos_aires = Location.find_by(city: "Buenos Aires")
Attraction.create(:name => "Buenos Aires Metropolitan Cathedral", :description => "The Buenos Aires Metropolitan Cathedral (Spanish: Catedral Metropolitana de Buenos Aires) is the main Catholic church in Buenos Aires, Argentina. It is located in the city center, overlooking Plaza de Mayo, on the corner of San Martín and Rivadavia streets, in the San Nicolás neighbourhood. It is the mother church of the Archdiocese of Buenos Aires.

The Cathedral of Buenos Aires was rebuilt several times since its humble origins in the 16th century. The present building is a mix of architectural styles, with an 18th-century nave and dome and a severe, 19th-century Neoclassical façade without towers. The interior keeps precious 18th-century statues and altarpieces, as well as abundant Neo-Renaissance and Neo-Baroque decoration.", :attraction_type => "Landmarks" ,:location => buenos_aires)
Attraction.create(:name => "Obelisco de Buenos Aires", :description => "The Obelisco de Buenos Aires (Obelisk of Buenos Aires) is a national historic monument and icon of Buenos Aires. Located in the Plaza de la República, in the intersection of avenues Corrientes and 9 de Julio, it was built to commemorate the fourth centenary of the first foundation of the city.

In order to enrich the surroundings of the iconic monument, the government of the city started the project Punto Obelisco, creating a zone full of LED signs. Since the Obelisk of the city is always associated with the night and entertainment of Buenos Aires, this project creates a zone similar to Times Square in New York and Piccadilly Circus in London.", :attraction_type => "Landmarks" ,:location => buenos_aires)
Attraction.create(:name => "Teatro Colón", :description => "The Teatro Colón (Spanish) (Colón Theatre) is the main opera house in Buenos Aires, Argentina. It is ranked the third best opera house in the world by National Geographic, and is acoustically considered to be amongst the five best concert venues in the world. The other venues are Berlin's Konzerthaus, Vienna's Musikverein, the Concertgebouw in Amsterdam, and Boston's Symphony Hall.

The present Colón replaced an original theatre which opened in 1857. Towards the end of the century it became clear that a new theatre was needed and, after a 20-year process, the present theatre opened on 25 May 1908, with Giuseppe Verdi's Aïda.

The Teatro Colón was visited by the foremost singers and opera companies of the time, who would sometimes go on to other cities including Montevideo, Rio de Janeiro and São Paulo.

After this period of huge international success, the theatre's decline became clear and plans were made for massive renovations. After an initial start of works to restore the landmark in 2005, the theatre was closed for refurbishment from October 2006 to May 2010. It re-opened on 24 May 2010, with a programme for the 2010 season.", :attraction_type => "Landmarks" ,:location => buenos_aires)
Attraction.create(:name => "I Latina", :description => "Colombian siblings Santiago, Camilo and Laura Macías, created this fine dining restaurant to bring the best gastronomic flavors from the Caribbean coast of Colombia to Buenos Aires. Santiago is the chef of the restaurant. Laura and Camilo will be your hosts.Every Tuesday through Saturday evening, we offer a seven-course tasting menu in which you will discover different flavors and ingredients of the latin american cuisine, paired with the best Argentine wines. We are located in a beautiful house in the Villa Crespo neighborhood of Buenos Aires. Reservations are required and can be made by phone or email. We invite you to discover new flavors and enjoy a completely unique gastronomic experience.", :attraction_type => "Dining" ,:location => buenos_aires)
Attraction.create(:name => "La Bourgogne", :description => "La Bourgogne offers the best French cuisine in Buenos Aires, where the Grand Chef Relais & Châteaux Jean Paul Bondoux delights and surprises our most discerning customers.

In a refined and warm environment, guests enjoy his exquisite French and international dishes.", :attraction_type => "Dining" ,:location => buenos_aires)
Attraction.create(:name => "Chila", :description => "CHILA has gourmet cuisine with Argentinian products. CHILA has several prizes: Position 21th in the 50 best restaurant in latinamerica 2014, Position 28th in the 50 best Restauraants in Latinamerica 2013 (San Pellegrino guide), Best Argentinian Restaurant 2008 (Argentinian Academy of Gastronomy), CHEF of the Future 2009 (International Academy of Gastronomy, Best Restaurant 2010 (Cuisine & Vins).", :attraction_type => "Dining" ,:location => buenos_aires)
Attraction.create(:name => "Buenos Aires Zoo", :description => "The Buenos Aires Zoo is an 45-acre (18 ha) zoo in the Palermo district of Buenos Aires, Argentina. The Zoo contains 89 species of mammals, 49 species of reptiles and 175 species of birds, with a total of over 2,500 different animals. The institution's goals are to conserve species, produce research and to educate the public.", :attraction_type => "Other" ,:location => buenos_aires)
Attraction.create(:name => "La Boca", :description => "La Boca is a neighborhood, or barrio of the Argentine capital, Buenos Aires. It retains a strong European flavour, with many of its early settlers being from the Italian city of Genoa. In fact the name has a strong assonance with the Genoese neighborhood of Boccadasse (or Bocadaze in Genoese dialect), and some people believe that the Buenos Aires barrio was indeed named after it. The conventional explanation is that the neighborhood sits at the mouth (\"boca\" in Spanish) of the Riachuelo.", :attraction_type => "Other" ,:location => buenos_aires)
Attraction.create(:name => "Flea Market Mercado de Pulgas", :description => "Right in the boundary between Palermo and Colegiales is the flea market. Inside this large warehouse, visitors will find numerous stalls selling antiquities, furniture, light fixtures, silverware, collectors' items and decorative objects, to name just a few of the offerings.", :attraction_type => "Other",:location => buenos_aires)
# Rome Attraction
rome = Location.find_by(city: "Rome")
Attraction.create(:name => "Colosseum", :description => "The Colosseum or Coliseum, also known as the Flavian Amphitheatre is an elliptical amphitheatre in the centre of the city of Rome, Italy. Built of concrete and stone, it is the largest amphitheatre in the world, and is considered one of the greatest works of architecture and engineering.

The Colosseum is situated just east of the Roman Forum. Construction began under the emperor Vespasian in 72 AD, and was completed in 80 AD under his successor and heir Titus. Further modifications were made during the reign of Domitian (81–96). These three emperors are known as the Flavian dynasty, and the amphitheatre was named in Latin for its association with their family name (Flavius).", :attraction_type => "Landmarks",:location => rome)
Attraction.create(:name => "Pantheon", :description => "The Pantheon is a building in Rome, Italy, commissioned by Marcus Agrippa during the reign of Augustus (27 BC - 14 AD) and rebuilt by the emperor Hadrian about 126 AD.

The building is circular with a portico of large granite Corinthian columns (eight in the first rank and two groups of four behind) under a pediment. A rectangular vestibule links the porch to the rotunda, which is under a coffered concrete dome, with a central opening (oculus) to the sky. Almost two thousand years after it was built, the Pantheon's dome is still the world's largest unreinforced concrete dome. The height to the oculus and the diameter of the interior circle are the same, 43.3 metres (142 ft).

It is one of the best-preserved of all Ancient Roman buildings. It has been in continuous use throughout its history, and since the 7th century, the Pantheon has been used as a church dedicated to \"St. Mary and the Martyrs\" but informally known as \"Santa Maria Rotonda\". The square in front of the Pantheon is called Piazza della Rotonda.", :attraction_type => "Landmarks",:location => rome)
Attraction.create(:name => "Trevi Fountain", :description => "The Trevi Fountain (Italian: Fontana di Trevi) is a fountain in the Trevi district in Rome, Italy, designed by Italian architect Nicola Salvi and completed by Pietro Bracci. Standing 26.3 metres (86 ft) high and 49.15 metres (161.3 ft) wide, it is the largest Baroque fountain in the city and one of the most famous fountains in the world. The fountain has appeared in several notable films, including Federico Fellini's La Dolce Vita, and is a popular tourist attraction.", :attraction_type => "Landmarks",:location => rome)
Attraction.create(:name => "La Pergola", :description => "Located at the elegant Rome Cavalieri hotel, La Pergola’s striking interior dining space is furnished with rare antiques and beautiful art from the hotel’s impressive collection, including magnificent paintings, tapestries and bespoke hand-blown glass pieces. It also features enormous windows, which showcase heart-stopping views of Rome. Extraordinary, innovative Mediterranean dishes – underpinned by fresh ingredients and a chef with an adventurous and passionate approach to food – are complemented by a wine cellar containing 53,000 bottles from 1888 to the present. For an unsurpassed, truly Roman summer experience, dine alfresco on the terrace in front of the twinkling panorama of the city. After-dinner drinks can be enjoyed in the exclusive adjoining Cigar Lounge, where vintage liqueurs are served.", :attraction_type => "Dining",:location => rome)
Attraction.create(:name => "Imàgo", :description => "As you indulge in the restaurant’s sophisticated seasonal dishes the exceptional 6th floor location provides a spectacular rooftop panorama of ancient Rome, for a breathtaking dining ambiance.", :attraction_type => "Dining",:location => rome)
Attraction.create(:name => "Il Pagliaccio", :description => "It offers clever Italian fusion in a sophisticated contemporary setting and, with space for just 28 diners, it’s always an exclusive gourmet experience. With an impeccable culinary pedigree and a central Rome location, Il Pagliaccio is the perfect place for a business dinner – private dining is available for eight to ten people.", :attraction_type => "Dining",:location => rome)
Attraction.create(:name => "Spanish Steps", :description => "The Spanish Steps (Italian: Scalinata della Trinità dei Monti) are a set of steps in Rome, Italy, climbing a steep slope between the Piazza di Spagna at the base and Piazza Trinità dei Monti, dominated by the Trinità dei Monti church at the top.

The monumental stairway of 135 steps (the slightly elevated drainage system is often mistaken for the first step) was built with French diplomat Étienne Gueffier’s bequeathed funds of 20,000 scudi, in 1723–1725, linking the Bourbon Spanish Embassy, and the Trinità dei Monti church that was under the patronage of the Bourbon kings of France, both located above — to the Holy See in Palazzo Monaldeschi located below. The stairway was designed by architects Francesco de Sanctis and Alessandro Specchi.", :attraction_type => "Other",:location => rome)
Attraction.create(:name => "Piazza Navona", :description => "Piazza Navona is a city square in Rome, Italy. It is built on the site of the Stadium of Domitian, built in 1st century AD, and follows the form of the open space of the stadium. The ancient Romans came there to watch the agones (\"games\"), and hence it was known as \"Circus Agonalis\" (\"competition arena\"). It is believed that over time the name changed to in avone to navone and eventually to navona.", :attraction_type => "Other",:location => rome)
Attraction.create(:name => "The Vatican Museums", :description => "The Vatican Museums are the museums of the Vatican City and are located within the city's boundaries. They display works from the immense collection built up by the Popes throughout the centuries including some of the most renowned classical sculptures and most important masterpieces of Renaissance art in the world.

Pope Julius II founded the museums in the early 16th century. The Sistine Chapel with its ceiling decorated by Michelangelo and the Stanze della Segnatura decorated by Raphael are on the visitor route through the Vatican Museums. In 2013, they were visited by 5.5 million people, which combined makes it the 5th most visited art museum in the world.

There are 54 galleries, or salas, in total, with the Sistine Chapel, notably, being the very last sala within the Museum.", :attraction_type => "Other",:location => rome)
# Berlin Attractions
berlin = Location.find_by(city: "Berlin")
Attraction.create(:name => "Berlin Wall", :description => "The Berlin Wall was a barrier that divided Berlin from 1961 to 1989, constructed by the German Democratic Republic (GDR, East Germany) starting on 13 August 1961, that completely cut off (by land) West Berlin from surrounding East Germany and from East Berlin until it was opened in November 1989. Its demolition officially began on 13 June 1990 and was completed in 1992. The barrier included guard towers placed along large concrete walls, which circumscribed a wide area (later known as the \"death strip\") that contained anti-vehicle trenches, \"fakir beds\" and other defenses. The Eastern Bloc claimed that the wall was erected to protect its population from fascist elements conspiring to prevent the \"will of the people\" in building a socialist state in East Germany. In practice, the Wall served to prevent the massive emigration and defection that marked East Germany and the communist Eastern Bloc during the post-World War II period.", :attraction_type => "Landmarks",:location => berlin)
Attraction.create(:name => "Brandenburg Gate", :description => "The Brandenburg Gate (German: Brandenburger Tor) is an 18th-century neoclassical triumphal arch in Berlin, and one of the best-known landmarks of Germany. It is built on the site of a former city gate that marked the start of the road from Berlin to the town of Brandenburg an der Havel.

It is located in the western part of the city centre of Berlin, at the junction of Unter den Linden and Ebertstraße, immediately west of the Pariser Platz. One block to the north stands the Reichstag building. The gate is the monumental entry to Unter den Linden, the renowned boulevard of linden trees, which formerly led directly to the city palace of the Prussian monarchs.", :attraction_type => "Landmarks",:location => berlin)
Attraction.create(:name => "Reichstag building", :description => "The Reichstag building is a historical edifice in Berlin, Germany, constructed to house the Imperial Diet (German: Reichstag), of the German Empire. It was opened in 1894 and housed the Diet until 1933, when it was severely damaged in a fire. After World War II, the building fell into disuse; the parliament of the German Democratic Republic (the Volkskammer) met in the Palast der Republik in East Berlin, while the parliament of the Federal Republic of Germany (the Bundestag) met in the Bundeshaus in Bonn.

The ruined building was made safe against the elements and partially refurbished in the 1960s, but no attempt at full restoration was made until after German reunification on 3 October 1990, when it underwent a reconstruction led by architect Norman Foster. After its completion in 1999, it once again became the meeting place of the German parliament: the modern Bundestag.", :attraction_type => "Landmarks",:location => berlin)
Attraction.create(:name => "Kater Schmaus", :description => "A gritty stairwell leads up to this hidden third floor restaurant in KaterHolzig—a graffiti-covered soap factory reinvented into a sprawling cultural center. Inside, there’s a state-of-the-art open kitchen filled with a staff that looks more like DJs than sous-chefs. The menu features mostly German-inspired dishes made with seasonal ingredients such as spinach–Alpine cheese dumplings with fresh mushrooms and a red beet salad. Desserts are especially good, even though they might sound like haikus, such as this offering: Black currants, Cigarette Fillo rolls, New York Cheesecake, Cucumber.", :attraction_type => "Dining",:location => berlin)
Attraction.create(:name => "Katz Orange", :description => "Those familiar with Berlin in the ‘90s might recognize this restaurant’s previous incarnation, the Maxwell, which was one of pioneers in the now über-trendy Mitte district. Currently headed by Daniel Finke, an ambitious German chef, the space is tucked away off an intimate courtyard and inside a beautiful brick historic building. The decor recalls the living room of a Sante Fe art collector, with mismatched vintage furniture and kilim throw pillows. Finke uses organic local ingredients to create a tight menu of deceptively simple dishes, like slow-cooked pork with seasonal vegetables. The bread is from the best baker in town, Soluna Brot & Oel, and the perfect french fries are cooked in goose fat.", :attraction_type => "Dining",:location => berlin)
Attraction.create(:name => "Pauly Saal", :description => "The biggest and buzziest restaurant opening of 2012 is an ode to classic German cuisine, located in a renovated Jewish girls’ school (now occupied by high-end art galleries). Overseen by Stephan Landwehr and Boris Radczun, the dapper duo behind Berlin’s most glamorous restaurant, the Grill Royal, the Pauly Saal was imagined as a classic bistro that might have existed in Berlin in the Golden ‘20s: leather booths, pine green fabric-covered chairs, walls covered in handmade ceramic tiles, and enormous Murano chandeliers. Austrian chef Siegfried Danler was imported from his Michelin-starred restaurant in Portugal to conceive the upscale family-style menu with entrees like ox steak or skate with spinach, sunchokes and crab. Almost everything is handmade on site, from the bread to the sausages.", :attraction_type => "Dining",:location => berlin)
Attraction.create(:name => "Fernsehturm Berlin", :description => "The Fernsehturm (English: Berlin TV Tower) is a television tower in central Berlin, Germany.

Close to Alexanderplatz in Berlin, the tower was constructed between 1965 and 1969 by the administration of the German Democratic Republic. It was intended as a symbol of Berlin, which it remains today, as it is easily visible throughout the central and some suburban districts of Berlin. With its height of 368 meters, it is the tallest structure in Germany.

The tower has become one of the most prominent symbols of the country and is often in the establishing shot of films set in Berlin. Due to its location near Alexanderplatz, the tower is occasionally called Alex Tower.", :attraction_type => "Other",:location => berlin)
Attraction.create(:name => "Berlin Zoological Garden", :description => "The Berlin Zoological Garden is the oldest and best known zoo in Germany. Opened in 1844 it covers 35 hectares (86.5 acres) and is located in Berlin's Tiergarten. With about 1,500 different species and almost 20,500 animals the zoo presents the most comprehensive collection of species in the world.

The zoo and its aquarium had more than 3 million visitors in 2013. It is considered to be the most visited zoo in Europe and one of the most popular worldwide. Regular animal feedings are among its most famous attractions. Globally known animals like Knut, the polar bear, and Bao Bao, the Giant Panda have contributed to the zoo's public image.

The zoo collaborates with many universities, research institutes, and other zoos around the world. It maintains and promotes European breeding programmes, helps safeguard several endangered species, and participates in several species reintroduction programs.", :attraction_type => "Other",:location => berlin)
Attraction.create(:name => "German Museum of Technology", :description => "Deutsches Technikmuseum Berlin (German Museum of Technology) in Berlin, Germany is a museum of science and technology, and exhibits a large collection of historical technical artifacts. The museum's main emphasis originally was on rail transport, but today it also features exhibits of various sorts of industrial technology. Recently, it has opened both maritime and aviation exhibition halls. The museum also contains a science center called Spectrum.", :attraction_type => "Other",:location => berlin)
# London Attractions
london = Location.find_by(city: "London")
Attraction.create(:name => "Big Ben", :description => "Big Ben is the nickname for the Great Bell of the clock at the north end of the Palace of Westminster in London, and often extended to refer to the clock and the clock tower.

The tower is officially known as the Elizabeth Tower, renamed as such to celebrate the Diamond Jubilee of Elizabeth II (prior to being renamed in 2012 it was known as simply \"Clock Tower\"). The tower holds the second largest four-faced chiming clock in the world (Minneapolis City Hall being the first). The tower was completed in 1858 and had its 150th anniversary on 31 May 2009, during which celebratory events took place. The tower has become one of the most prominent symbols of the United Kingdom and is often in the establishing shot of films set in London.", :attraction_type => "Landmarks",:location => london)
Attraction.create(:name => "Palace of Westminster", :description => "The Palace of Westminster is the meeting place of the House of Commons and the House of Lords, the two houses of the Parliament of the United Kingdom. Commonly known as the Houses of Parliament after its occupants, the Palace lies on the Middlesex bank of the River Thames in the City of Westminster, in central London. Its name, which derives from the neighbouring Westminster Abbey, may refer to either of two structures: the Old Palace, a medieval building complex that was destroyed by fire in 1834, and its replacement, the New Palace that stands today. For ceremonial purposes, the palace retains its original style and status as a royal residence and is the property of the Crown.", :attraction_type => "Landmarks",:location => london)
Attraction.create(:name => "Tower Bridge", :description => "Tower Bridge (built 1886–1894) is a combined bascule and suspension bridge in London, England which crosses the River Thames. It is close to the Tower of London, from which it takes its name, and has become an iconic symbol of London.

The bridge consists of two bridge towers tied together at the upper level by two horizontal walkways, designed to withstand the horizontal forces exerted by the suspended sections of the bridge on the landward sides of the towers. The vertical components of the forces in the suspended sections and the vertical reactions of the two walkways are carried by the two robust towers. The bascule pivots and operating machinery are housed in the base of each tower. The bridge's present colour scheme dates from 1977, when it was painted red, white and blue for Queen Elizabeth II's Silver Jubilee. Originally it was painted a mid greenish-blue colour.", :attraction_type => "Landmarks",:location => london)
Attraction.create(:name => "Gymkhana", :description => "Gymkhana
Without a doubt the most elegant Indian restaurant in London, Gymkhana has a stunning lacquered oak ceiling and an aged-brass bar. Coriander-and-ginger-scented scallops are among chef Karam Sethi's delicately spiced dishes.", :attraction_type => "Dining",:location => london)
Attraction.create(:name => "The Magazine", :description => "Berlin-born, Japan-trained chef Oliver Lange adds truffles to sushi and crisped amaranth to beet sorbet with yogurt. Starchitect Zaha Hadid designed the space, inside the Serpentine Sackler art gallery, with her signature undulating glass walls.", :attraction_type => "Dining",:location => london)
Attraction.create(:name => "Story", :description => "Chef Tom Sellers, a 27-year-old Noma and Per Se alum, opened this restaurant a year ago, and now it's one of the city's toughest reservations. The dishes are nostalgic British yet forward-thinking, starting with the already iconic Bread & Dripping, involving a melting candle made of beef fat. ", :attraction_type => "Dining",:location => london)
Attraction.create(:name => "The London Eye", :description => "The London Eye is a giant Ferris wheel on the South Bank of the River Thames in London. Also known as the Millennium Wheel, its official name was originally published as the British Airways London Eye, then the Merlin Entertainments London Eye, then the EDF Energy London Eye. Since mid-January 2015, it has been known in branding as the Coca-Cola London Eye, following an agreement signed in September 2014.

The entire structure is 135 metres (443 ft) tall and the wheel has a diameter of 120 metres (394 ft). When erected in 1999 it was the world's tallest Ferris wheel. Its height was surpassed by the 160 m (520 ft) Star of Nanchang in 2006, the 165 m (541 ft) Singapore Flyer in 2008, and the 167.6 m (550 ft) High Roller (Las Vegas) in 2014. Supported by an A-frame on one side only, unlike the taller Nanchang and Singapore wheels, the Eye is described by its operators as \"the world's tallest cantilevered observation wheel\".", :attraction_type => "Other",:location => london)
Attraction.create(:name => "Madame Tussauds London", :description => "Madame Tussauds London is a museum and tourist attraction located in Central London, housed in the former London Planetarium. It is known for recreating life size wax models of celebrities. The attraction houses its famous Chamber of Horrors. Set up by wax sculptor Marie Tussaud on Marylebone Road in 1884 it is the first Madame Tussauds.", :attraction_type => "Other",:location => london)
Attraction.create(:name => "Hyde Park", :description => "Hyde Park is one of the largest parks in London, and one of the Royal Parks of London, famous for its Speakers' Corner.

The park was the site of the Great Exhibition of 1851, for which the Crystal Palace was designed by Joseph Paxton. The park has become a traditional location for mass demonstrations. The Chartists, the Reform League, the Suffragettes, and the Stop the War Coalition have all held protests in the park. Many protesters on the Liberty and Livelihood March in 2002 started their march from Hyde Park. On 20 July 1982 in the Hyde Park and Regents Park bombings, two bombs linked to the Provisional Irish Republican Army caused the death of eight members of the Household Cavalry and the Royal Green Jackets and seven horses.", :attraction_type => "Other",:location => london)
# Prague Attractions
prague = Location.find_by(city: "Prague")
Attraction.create(:name => "Charles Bridge", :description => "The Charles Bridge is a famous historic bridge that crosses the Vltava river in Prague, Czech Republic. Its construction started in 1357 under the auspices of King Charles IV, and finished in the beginning of the 15th century. The bridge replaced the old Judith Bridge built 1158–1172 that had been badly damaged by a flood in 1342. This new bridge was originally called the Stone Bridge (Kamenný most) or the Prague Bridge (Pražský most) but has been the \"Charles Bridge\" since 1870. As the only means of crossing the river Vltava (Moldau) until 1841, the Charles Bridge was the most important connection between Prague Castle and the city's Old Town and adjacent areas. This \"solid-land\" connection made Prague important as a trade route between Eastern and Western Europe.", :attraction_type => "Landmarks",:location => prague)
Attraction.create(:name => "Old Town Square", :description => "Old Town Square is a historic square in the Old Town quarter of Prague, the capital of the Czech Republic.

It is located between Wenceslas Square and the Charles Bridge and features various architectural styles including the Gothic Týn Church and baroque St. Nicholas Church. Among many churches, tourists may find the Prague Astronomical Clock on this square, while the tower at the Old Town Hall offers a panoramic view of Old Town shop. An art museum of the Czech National Gallery is located in Kinský Palace.", :attraction_type => "Landmarks",:location => prague)
Attraction.create(:name => "Prague Castle", :description => "Prague Castle is the official residence and office of the President of the Czech Republic. Located in the Hradčany district of Prague and dating back to the ninth century, the castle has been a seat of power for kings of Bohemia, Holy Roman emperors, and presidents of Czechoslovakia. The Bohemian Crown Jewels are kept within a hidden room inside it.

The Guinness Book of Records lists Prague Castle as the largest ancient castle in the world. It occupies an area of almost 70,000 m2, at about 570 meters in length and an average of about 130 meters wide.", :attraction_type => "Landmarks",:location => prague)
Attraction.create(:name => "Dynamo", :description => "This sleek, lime green diner in Nové Mesto (New Town) has an award-winning design that includes chrome accents, a large digital clock, cone-shaped glass light fixtures, and rotating contemporary art.", :attraction_type => "Dining",:location => prague)
Attraction.create(:name => "Arzenal", :description => "One of the most unusual and colorful shops to be found in the city is Arzenal, a Thai restaurant selling glass works by renowned Czech designer and architect, Boris Sípek.", :attraction_type => "Dining",:location => prague)
Attraction.create(:name => "Divinis", :description => "Located on a quiet cobblestoned street near the Tyn Church, this cozy Italian wine bar is owned by Czech celebrity chef Zdeněk Pohlreich.", :attraction_type => "Dining",:location => prague)
Attraction.create(:name => "National Museum", :description => "The National museum is a Czech museum institution intended to systematically establish, prepare and publicly exhibit natural scientific and historical collections. It was founded 1818 in Prague by Kašpar Maria Šternberg. Historian František Palacký was also strongly involved.

At present the National Museum houses almost 14 million items from the area of natural history, history, arts, music and librarianship, located in tens of buildings.", :attraction_type => "Other",:location => prague)
Attraction.create(:name => "St. Vitus Cathedral", :description => "The Metropolitan Cathedral of Saints Vitus, Wenceslaus and Adalbert is a Roman Catholic metropolitan cathedral in Prague, the seat of the Archbishop of Prague. Up to 1997, the cathedral was dedicated only to Saint Vitus, and is still commonly named only as St. Vitus Cathedral.

This cathedral is an excellent example of Gothic architecture and is the biggest and most important church in the country. Located within Prague Castle and containing the tombs of many Bohemian kings and Holy Roman Emperors, the cathedral is under the ownership of the Czech government as part of the Prague Castle complex. Cathedral dimensions are 124 × 60 meters, the main tower is 96.5 meters high, front towers 82 m, arch height 33.2 m.", :attraction_type => "Other",:location => prague)
Attraction.create(:name => "Prague astronomical clock", :description => "The Prague astronomical clock, or Prague orloj, is a medieval astronomical clock located in Prague, the capital of the Czech Republic. The clock was first installed in 1410, making it the third-oldest astronomical clock in the world and the oldest one still working.", :attraction_type => "Other",:location => prague)
# Hanoi Attractions
hanoi = Location.find_by(city: "Hanoi")
Attraction.create(:name => "Hoan Kiem Lake", :description => "Hoan Kiem Lake is a lake in the historical center of Hanoi, the capital city of Vietnam. The lake is one of the major scenic spots in the city and serves as a focal point for its public life.", :attraction_type => "Landmarks",:location => hanoi)
Attraction.create(:name => "Tran Quoc Pagoda", :description => "Tran Quoc Pagoda, the oldest Buddhist temple in Hanoi, is located on a small island near the southeastern shore of Hanoi's West Lake, Vietnam.", :attraction_type => "Landmarks",:location => hanoi)
Attraction.create(:name => "One Pillar Pagoda", :description => "The One Pillar Pagoda is a historic Buddhist temple in Hanoi, the capital of Vietnam. It is regarded alongside the Perfume Temple, as one of Vietnam's two most iconic temples.

The temple was built by Emperor Lý Thái Tông, who ruled from 1028 to 1054. According to the court records, Lý Thái Tông was childless and dreamt that he met the bodhisattva Avalokiteshvara, who handed him a baby son while seated on a lotus flower. Lý Thái Tông then married a peasant girl that he had met and she bore him a son. The emperor constructed the temple in gratitude for this in 1049, having been told by a monk named Thiền Tuệ to build the temple, by erecting a pillar in the middle of a lotus pond, similar to the one he saw in the dream.", :attraction_type => "Landmarks",:location => hanoi)
Attraction.create(:name => "Banh Mi 25", :description => "You will not be disappointed by stopping off here.

The Bahn Mi is the best in Vietnam and the service is excellent. It's also affordable, about a dollar for each one.

Food is all fresh and you can see us preparing it.", :attraction_type => "Dining",:location => hanoi)
Attraction.create(:name => "French Grill", :description => "Inspired classics... The restaurant offers 82 seats in a simplistic modern design and lively setting, a semi-private and a private dining room, walk-in wine cooler with a selection of the finest wines in the world, and one of the largest open kitchen in Hanoi to complete this must see eatery in town. True French classics combined with the best to offer from the grill, prepared with the very best of products available in Vietnam. Open daily for dinner: 18:00 - 22:30", :attraction_type => "Dining",:location => hanoi)
Attraction.create(:name => "Essence Restaurant", :description => "Located on the ground floor of the Essence Hanoi Hotel & Spa, the artfully designed Essence restaurant offers you various tasty authentic Vietnamese dishes and standard Western menu for lunch and dinner. Accomplished with an extensive menu of beverages including fresh fruit shakes, coffees and wines, the restaurant ensures you a wholesome meal with great food, excellent service in the right ambiance and fine spirits, all at a price guaranteed most reasonable in town. Wifi-internet & iMac is available, free of charge.", :attraction_type => "Dining",:location => hanoi)
Attraction.create(:name => "Trúc Bạch Lake", :description => "Trúc Bạch Lake is one of the many lakes in the city of Hanoi, the capital of Vietnam. It is known outside Vietnam as the site where future United States politician John McCain landed during the Vietnam War after being shot down.

Trúc Bạch Lake is located northwest of Hanoi's Old Quarter, immediately adjacent to the eastern shore of the city's largest lake, the West Lake (Hồ Tây), a former branch of the Red River whose west bank is nearby. Trúc Bạch Lake was separated from the West Lake by the construction of a narrow dike in the 17th century to allow raising fish. The inhabitants of the Truc Yen Village, located on the south shore of the newly formed lake, were in the business of making bamboo blinds and hence cultivated a small variety of bamboo.[1] In 1957 and 1958, major Thanh Niên Road was built between the lakes. In 1730s, the Trịnh Lord Trịnh Giang had Trúc Lâm Palace constructed on the lake shore. The building first served as a pleasure palace but was later converted into a prison for royal concubines found guilty of crime. The silk they produced, known as \"Bamboo Village Silk\" became famous for its beauty.", :attraction_type => "Other",:location => hanoi)
Attraction.create(:name => "St. Joseph's Cathedral", :description => "St. Joseph's Cathedral is a church on Nha Tho (Church) Street in the Hoàn Kiếm District of Hanoi, Vietnam. The late 19th-century Gothic Revival (Neo-Gothic style) church serves as the cathedral of the Roman Catholic Archdiocese of Hanoi to nearly 4 million Catholics in the country.", :attraction_type => "Other",:location => hanoi)
Attraction.create(:name => "Ho Chi Minh Mausoleum", :description => "The Ho Chi Minh Mausoleum is a large memorial in Hanoi, Vietnam. It is located in the centre of Ba Dinh Square, which is the place where Vietminh leader Ho Chi Minh, Chairman of the Communist Party of Vietnam from 1951 until his death in 1969, read the Declaration of Independence on 2 September 1945, establishing the Democratic Republic of Vietnam. Ba Đình Mausoleum  was ranked as the \"sixth most ugly\" building in the world by CNN International in 2012.", :attraction_type => "Other",:location => hanoi)
# Istanbul Attractions
istanbul = Location.find_by(city: "Istanbul")
Attraction.create(:name => "Sultan Ahmed Mosque", :description => "The Sultan Ahmed Mosque is a historic mosque in Istanbul. The mosque is popularly known as the Blue Mosque for the blue tiles adorning the walls of its interior.

It was built from 1609 to 1616, during the rule of Ahmed I. Its Külliye contains a tomb of the founder, a madrasah and a hospice. The Sultan Ahmed Mosque is still popularly used as a mosque.", :attraction_type => "Landmarks",:location => istanbul)
Attraction.create(:name => "Hagia Sophia", :description => "Hagia Sophia is a former Greek Orthodox patriarchal basilica (church), later an imperial mosque, and now a museum (Ayasofya Müzesi) in Istanbul, Turkey. From the date of its construction in 537 until 1453, it served as an Eastern Orthodox cathedral and seat of the Patriarchate of Constantinople, except between 1204 and 1261, when it was converted to a Roman Catholic cathedral under the Latin Empire. The building was a mosque from 29 May 1453 until 1931. It was then secularized and opened as a museum on 1 February 1935.", :attraction_type => "Landmarks",:location => istanbul)
Attraction.create(:name => "Topkapı Palace", :description => "The Topkapı Palace is a large palace in Istanbul, Turkey, that was the primary residence of the Ottoman sultans for approximately 400 years (1465–1856) of their 624-year reign.", :attraction_type => "Landmarks",:location => istanbul)
Attraction.create(:name => "Cipriani Istanbul", :description => "The secret of Cipriani isn’t about what can be seen or touched, but what can be felt and sensed. It is intangible but palpable. It can’t be patented, but even after 75 years it hasn’t been duplicated by others.

The most popular dishes are: The World-Famous Bellini Cocktail, the exquisite Carpaccio, perfect sandwiches and ice creams to die for – all take their place among the pastas and risottos, the fish and Mediterranean vegetables that make up some of the world’s finest food.", :attraction_type => "Dining",:location => istanbul)
Attraction.create(:name => "Changa", :description => "Using ingredients from across the globe, consultant chef Peter Gordon produces fresh interpretations of classic Turkish dishes. A range of textures and ingredients are successfully harmonized, with no single flavor dominating. Within walking distance from Taksim Square, Changa occupies four floors of a stunning 103-year-old Art Nouveau townhouse. For special occasions hire the beautiful private dining room on the top floor for 12-30 people. Hand painted in the early 1900s, the room’s walls and ceilings have been left untouched. Changa is open from October to June.", :attraction_type => "Dining",:location => istanbul)
Attraction.create(:name => "Müzedechanga", :description => "Unlike Changa’s Art Nouveau townhouse, Müzedechanga is located in a ‘glass box’ building with 20th century Scandinavian décor and furniture by award-winning Turkish design duo Autoban. Müzedechanga serves a light all-day menu for museum visitors and transforms into a fine dining restaurant in the evening. Open all year, Müzedechanga seats 80 and accommodates 140 on the terrace in summer.", :attraction_type => "Dining",:location => istanbul)
Attraction.create(:name => "Istanbul Archaeology Museums", :description => "The Istanbul Archaeology Museums is a group of three archeological museums located in the Eminönü district of Istanbul, Turkey, near Gülhane Park and Topkapı Palace. The Istanbul Archaeology Museums consists of three museums: Archaeological Museum (in the main building), Museum of the Ancient Orient, Museum of Islamic Art (in the Tiled Kiosk). It houses over one million objects that represent almost all of the eras and civilizations in world history.", :attraction_type => "Other",:location => istanbul)
Attraction.create(:name => "Grand Bazaar", :description => "The Grand Bazaar in Istanbul is one of the largest and oldest covered markets in the world, with 61 covered streets and over 3,000 shops which attract between 250,000 and 400,000 visitors daily. In 2014, it is listed No.1 among world's most-visited tourist attractions with 91,250,000 annual visitors.", :attraction_type => "Other",:location => istanbul)
Attraction.create(:name => "Golden Horn", :description => "The Golden Horn, also known by its modern Turkish name as Haliç, is a major urban waterway and the primary inlet of the Bosphorus in Istanbul, Turkey. It is a horn-shaped estuary that joins Bosphorus Strait at the immediate point where said strait meets the Sea of Marmara, thus forming a narrow, isolated peninsula, the tip of which is \"Old Istanbul\" (ancient Byzantion and Constantinople), and the promontory of Sarayburnu, or Seraglio Point. The Golden Horn geographically separates the historic center of Istanbul from the rest of the city, and forms a natural, sheltered harbor that has historically protected Greek, Roman, Byzantine, Ottoman and other maritime trade ships for thousands of years.", :attraction_type => "Other",:location => istanbul)
# Siem Reap Attractions
siem_reap = Location.find_by(city: "Siem Reap")
Attraction.create(:name => "Angkor Wat", :description => "Angkor Wat was first a Hindu, later a Buddhist, temple complex in Cambodia and the largest religious monument in the world. The temple was built by the Khmer King Suryavarman II in the early 12th century in Yaśodharapura, the capital of the Khmer Empire, as his state temple and eventual mausoleum. Breaking from the Shaiva tradition of previous kings, Angkor Wat was instead dedicated to Vishnu. As the best-preserved temple at the site, it is the only one to have remained a significant religious center since its foundation. The temple is at the top of the high classical style of Khmer architecture. It has become a symbol of Cambodia, appearing on its national flag, and it is the country's prime attraction for visitors.", :attraction_type => "Landmarks",:location => siem_reap)
Attraction.create(:name => "Angkor Thom", :description => "Angkor Thom, located in present day Cambodia, was the last and most enduring capital city of the Khmer empire. It was established in the late twelfth century by King Jayavarman VII. It covers an area of 9 km², within which are located several monuments from earlier eras as well as those established by Jayavarman and his successors. At the centre of the city is Jayavarman's state temple, the Bayon, with the other major sites clustered around the Victory Square immediately to the north.", :attraction_type => "Landmarks",:location => siem_reap)
Attraction.create(:name => "Bayon", :description => "The Bayon is a well-known and richly decorated Khmer temple at Angkor in Cambodia. Built in the late 12th or early 13th century as the official state temple of the Mahayana Buddhist King Jayavarman VII, the Bayon stands at the centre of Jayavarman's capital, Angkor Thom. Following Jayavarman's death, it was modified and augmented by later Hindu and Theravada Buddhist kings in accordance with their own religious preferences.", :attraction_type => "Landmarks",:location => siem_reap)
Attraction.create(:name => "Bayon Restaurant", :description => "Next door to Mom's Guesthouse, just off National Hightway 6, Siem Reap. The Bayon has a pleasant garden setting and consistently excellent food. Try the popular curry chicken in coconut.", :attraction_type => "Dining",:location => siem_reap)
Attraction.create(:name => "Chivit Thai", :description => "This is the best restaurant in town for Thai food. The setting is delightfully traditional with raised eating platforms and the extensive menu offers all the favourites.", :attraction_type => "Dining",:location => siem_reap)
Attraction.create(:name => "Cuisine Wat Damnak", :description => "Arguably the best Khmer cuisine in town, often with a modern twist.", :attraction_type => "Dining",:location => siem_reap)
Attraction.create(:name => "Cambodian Cultural Village", :description => "Cambodian Cultural Village (CCV) is a theme park and museum in Siem Reap, Cambodia. It is located on the road to and from the airport, 6 km from the town.

The theme park was constructed in 2001 and opened to the public on 24 September 2003. It covers a total area of 210,000 square meters. The CCV presents miniature versions of important historical buildings and structures, together with local customs. There are eleven unique villages, representing the varied culture heritage of nineteen ethnic groups. At each village are wood houses, carvings in stone, traditional performances in different styles such as: Apsara dancing, performances of ethnic minorities from the north-east of Cambodia, traditional wedding ceremony, circus, folk games, peacock dancing, acrobats, elephant shows, boxing and more.", :attraction_type => "Other",:location => siem_reap)
Attraction.create(:name => "Preah Khan", :description => "Preah Khan is a temple at Angkor, Cambodia, built in the 12th century for King Jayavarman VII. It is located northeast of Angkor Thom and just west of the Jayatataka baray, with which it was associated. It was the centre of a substantial organisation, with almost 100,000 officials and servants. The temple is flat in design, with a basic plan of successive rectangular galleries around a Buddhist sanctuary complicated by Hindu satellite temples and numerous later additions. Like the nearby Ta Prohm, Preah Khan has been left largely unrestored, with numerous trees and other vegetation growing among the ruins.", :attraction_type => "Other",:location => siem_reap)
Attraction.create(:name => "Banteay Srei", :description => "Banteay Srei or Banteay Srey is a 10th-century Cambodian temple dedicated to the Hindu god Shiva. Located in the area of Angkor in Cambodia. It lies near the hill of Phnom Dei, 25 km (16 mi) north-east of the main group of temples that once belonged to the medieval capitals of Yasodharapura and Angkor Thom. Banteay Srei is built largely of red sandstone, a medium that lends itself to the elaborate decorative wall carvings which are still observable today. The buildings themselves are miniature in scale, unusually so when measured by the standards of Angkorian construction. These factors have made the temple extremely popular with tourists, and have led to its being widely praised as a \"precious gem\", or the \"jewel of Khmer art.\"", :attraction_type => "Other",:location => siem_reap)
# Marrakech Attractions
marrakech = Location.find_by(city: "Marrakech")
Attraction.create(:name => "Jemaa el-Fnaa", :description => "Jamaa el Fna is a square and market place in Marrakesh's medina quarter (old city). It remains the main square of Marrakesh, used by locals and tourists.", :attraction_type => "Landmarks",:location => marrakech)
Attraction.create(:name => "Koutoubia Mosque", :description => "The Koutoubia Mosque or Kutubiyya Mosque is the largest mosque in Marrakesh, Morocco. The mosque is also known by several other names, such as Jami' al-Kutubiyah, Kotoubia Mosque, Kutubiya Mosque, Kutubiyyin Mosque, and Mosque of the Booksellers. It is located in the southwest medina quarter of Marrakesh. The mosque is ornamented with curved windows, a band of ceramic inlay, pointed merlons, and decorative arches; it has a large plaza with gardens, and is floodlit at night. The minaret, 77 metres (253 ft) in height, includes a spire and orbs. It was completed under the reign of the Almohad Caliph Yaqub al-Mansur (1184 to 1199), and has inspired other buildings such as the Giralda of Seville and the Hassan Tower of Rabat.", :attraction_type => "Landmarks",:location => marrakech)
Attraction.create(:name => "Majorelle Garden", :description => "The Majorelle Garden is a twelve-acre botanical garden and artist's landscape garden in Marrakech, Morocco. It was designed by the expatriate French artist Jacques Majorelle in the 1920s and 1930s, during the colonial period when Morocco was a protectorate of France.", :attraction_type => "Landmarks",:location => marrakech)
Attraction.create(:name => "The Amal Moroccan Restaurant and Women's Training Center", :description => "The Amal Women's Training Center and Moroccan Restaurant is a non-profit association dedicated to empowering disadvantaged women via training in traditional and modern cuisine. The ultimate goal is personal transformation, skill set re-enforcement, and job placement for economic and social stability.", :attraction_type => "Dining",:location => marrakech)
Attraction.create(:name => "Gastro MK at Maison MK", :description => "Fine-dining restaurant at boutique hotel maison mk. Open to internal & external guests for dinner.", :attraction_type => "Dining",:location => marrakech)
Attraction.create(:name => "Amaia Restaurant", :description => "Near the post office of Marrakesh Gueliz, on the Hassan 2 boulevard, the Amaia restaurant is Open from Monday to Saturday. Food is served all day. Eat in or take out, food is tasty, healthy, light and so are the prices. For lunch and dinner, in a cozy atmosphere, check out the large menu with its good wines and daily suggestions. At aperitif time, a large variety of cocktails and tapas are also available.", :attraction_type => "Dining",:location => marrakech)
Attraction.create(:name => "El Badi Palace", :description => "El Badi Palace is a ruined palace located in Marrakesh, Morocco. Commissioned by the Saadian sultan Ahmad al-Mansur, sometime shortly after his accession in 1578, its construction was funded by a substantial ransom paid by the Portuguese after the Battle of the Three Kings. The palace is nowadays a well known tourist attraction.", :attraction_type => "Other",:location => marrakech)
Attraction.create(:name => "Saadian Tombs", :description => "The Saadian tombs in Marrakech date back from the time of the sultan Ahmad al-Mansur (1578-1603). The tombs were discovered in 1917 and were restored by the Beaux-arts service. The tombs have, because of the beauty of their decoration, been a major attraction for visitors of Marrakech.

The mausoleum comprises the interments of about sixty members of the Saadi Dynasty that originated in the valley of the Draa River. Among the graves are those of Ahmad al-Mansur and his family. The building is composed of three rooms. The most famous is the room with the twelve columns. This room contains the grave of the son of the sultan's son, Ahmad al-Mansur. The stele is in finely worked cedar wood and stucco work. The monuments are made of Italian Carrara marble.", :attraction_type => "Other",:location => marrakech)
Attraction.create(:name => "Bahia Palace", :description => "The Bahia Palace is a palace and a set of gardens located in Marrakesh, Morocco. It was built in the late 19th century, intended to be the greatest palace of its time. The name means \"brilliance\". As in other buildings of the period in other countries, it was intended to capture the essence of the Islamic and Moroccan style. There is a 2 acre (8,000 m²) garden with rooms opening onto courtyards.

Set up at the end of 19th century by Si Moussa, grand vizier of the sultan, for his personal use, this palace would bear the name of one of his wives. Here, the harem, which includes a vast court decorated with a central basin and surrounded by rooms intended for the concubines. As the black slave Abu Ahmed rose to power and wealth towards the end of the 19th century, he had the Bahia palace built by bringing in craftsmen from Fez.", :attraction_type => "Other",:location => marrakech)
